language: ruby
rvm:
  - "2.1.1"
  - "1.9.3"
services: redis-server
env: 
  - "TEST_SIESTE_HOST=http://localhost:1234 TEST_SIESTE_ORIGIN=TRAVIS"
bundler_args: --without debugging production 
script: 
  - ruby simple_endpoint.rb > /dev/null 2>&1 &
  - ruby scripts/mock_sieste.rb > /dev/null 2>&1 &
  - xvfb-run --server-args="-screen 0 1024x768x24"  bundle exec rspec spec/*_spec.rb 
